name: RefreshV2Node

on:
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          check-latest: true
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install requests
      - name: Checkin
        run: |
          python3 RefreshV2Node.py 
