name: RefreshV2Node

on:
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Checkin
        run: |
          python3 RefreshV2Node.py 
