name: RefreshV2Node

on:
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          check-latest: true
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install requests
      - name: Run Python code RefreshV2Node.py
        run: python3 RefreshV2Node.py
      - name: Commit
        run: |
          git config --global user.email github_action@github.com
          git config --global user.name github_action
          git add .
          git commit -m "GitHub Action RefreshV2Node" -a
          git pull --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
