name: RefreshV2Node

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  refresh-v2-node:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip3 install requests
      - name: Run Python code RefreshV2Node.py
        run: python3 RefreshV2Node.py
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: GitHub Action RefreshV2Node
      - if: steps.git-auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changed!"
      - if: steps.git-auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
